package com.apex.plugins.toolpkg

// STUBBED: had 62 errors
object ToolPkgPromptHookBridge
object PromptInputBridge
object PromptHistoryBridge
object PromptEstimateHistoryBridge
object SystemPromptComposeBridge
object ToolPromptComposeBridge
object PromptFinalizeBridge
object PromptEstimateFinalizeBridge
