package com.apex.plugins.toolpkg

// Minimal implementation (had 61 errors)
object ToolPkgPromptHookBridge
object PromptInputBridge
object PromptHistoryBridge
object PromptEstimateHistoryBridge
object SystemPromptComposeBridge
object ToolPromptComposeBridge
object PromptFinalizeBridge
object PromptEstimateFinalizeBridge
